apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: experiment-data-pvc
  namespace: longweiwangusd
spec:
  storageClassName: rook-ceph-block  # Official Nautilus storage class
  accessModes:
    - ReadWriteOnce  # As per Nautilus documentation
  resources:
    requests:
      storage: 100Gi