apiVersion: batch/v1
kind: Job
metadata:
  name: adv-test-v1-lieconv-job
  namespace: longweiwangusd
spec:
  template:
    spec:
      containers:
      - name: lieconv-container
        image: continuumio/anaconda3:latest
        command: ["/bin/bash"]
        args: ["-c", "cd /data/lieconv && ./setup_lieconv.sh && source activate lieconv && python test_liecnv.py"]
        volumeMounts:
        - name: data-storage
          mountPath: /data
        - name: dshm
          mountPath: /dev/shm
        resources:
          requests:
            memory: "32Gi"
            cpu: "8"
            nvidia.com/rtxa6000: 1
          limits:
            memory: "32Gi"
            cpu: "16"
            nvidia.com/rtxa6000: 1
      volumes:
      - name: data-storage
        persistentVolumeClaim:
          claimName: experiment-data-pvc-shared
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: "16Gi"
      restartPolicy: Never
  backoffLimit: 1