apiVersion: batch/v1
kind: Job
metadata:
  name: imagenet-training-job
  namespace: longweiwangusd
spec:
  template:
    spec:
      containers:
      - name: training-container
        image: continuumio/anaconda3:latest
        command: ["/bin/bash"]
        args: ["-c", "cd /data && ./setup_environment.sh && source activate imagenet-exp && python imagenet_experiment.py"]
        volumeMounts:
        - name: data-storage
          mountPath: /data
        - name: dshm
          mountPath: /dev/shm
        resources:
          requests:
            memory: "32Gi"
            cpu: "8"
            nvidia.com/rtxa6000: 1
          limits:
            memory: "32Gi"
            cpu: "12"
            nvidia.com/rtxa6000: 1
      volumes:
      - name: data-storage
        persistentVolumeClaim:
          claimName: experiment-data-pvc
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: "8Gi"
      restartPolicy: Never
  backoffLimit: 1