apiVersion: batch/v1
kind: Job
metadata:
  name: brats20-download-job
  namespace: longweiwangusd
spec:
  template:
    spec:
      containers:
      - name: download-container
        image: continuumio/anaconda3:latest
        command: ["/bin/bash"]
        args: ["-c", "cd /data/brats && chmod +x brats_down_env.sh && ./brats_down_env.sh"]
        env:
        - name: KAGGLE_USERNAME
          value: "ifratmitul"
        - name: KAGGLE_KEY
          value: "cc5db889e9f22174190ff2b6d5c34fba"
        volumeMounts:
        - name: data-storage
          mountPath: /data
        resources:
          requests:
            memory: "48Gi"
            cpu: "4"
          limits:
            memory: "64Gi"
            cpu: "8"
      volumes:
      - name: data-storage
        persistentVolumeClaim:
          claimName: experiment-data-pvc-shared
      restartPolicy: Never
  backoffLimit: 0